#+TITLE: org-impress-js.el
#+AUTHOR: Takumi KINJO
#+OPTIONS: num:nil
#+IMPRESSJS_STYLE: http://kinjo.github.io/org-impress-js.el/resources/css/impress-demo.css
#+IMPRESSJS_SRC: http://kinjo.github.io/org-impress-js.el/resources/js/impress.js
#+HTML_HEAD: <link rel="stylesheet" href="http://kinjo.github.io/org-impress-js.el/resources/css/mystyle.css" type="text/css" />
* org-impress-js.el
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  This library implements a impress.js back-end for Org
  generic exporter based on ox-html.el.

  http://kinjo.github.io/org-impress-js.el/ is a demo page.

  * See http://orgmode.org/ about Org-mode.
  * See http://bartaz.github.io/impress.js/ about impress.js.

  I appreciate for their great works.

  This requires *Org-mode version 8.2.6* and *GNU Emacs 24 or higher*.

* INSTALLATION
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  1) First of all, check Org-mode version.
     This library has been tested on Org-mode 8.2.6.
     #+BEGIN_SRC text
       M-x org-version
     #+END_SRC

  2) Get org-impress-js.el. For example,
     #+BEGIN_SRC sh
       git clone https://github.com/kinjo/org-impress-js.el.git \
           ~/org-impress-js.el
     #+END_SRC

  3) Add following to ~/.emacs.d/init.el and reboot emacs.
     #+BEGIN_SRC emacs-lisp
       (add-to-list 'load-path "~/org-impress-js.el")
       (require 'ox-impress-js)
     #+END_SRC
* USAGE
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  Open README.org in your emacs.

  To convert to an impress.js HTML file, type C-c C-e.

  `*Org Export Dispatcher*' buffer will open, so follow the menu.

  If you type `j' and then `j', README.html will be generated.

  Open the file in your web browser.

  #+BEGIN_SRC sh
    cd ~/org-impress-js.el/
    open README.html
  #+END_SRC

* PROPERTIES
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  Following PROPERTIES are available.

  * data-x, data-y, data-z

    X, Y and Z position of the slide.

  * data-rotate-x, data-rotate-y, data-rotate-z

    Define the rotation of the slide around given axis in degrees.

  * trans-x, trans-y, trans-z

    Translate the slide to each axis.

  * rotate-x, rotate-y, rotate-z

    Rotate the slide to each axis in degrees.

* KNOWN ISSUES
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  The following properties does not work in the nested headlines
  because ox.el processes Org-mode file by the depth-first.

  * trans-x, trans-y, trans-z
  * rotate-x, rotate-y, rotate-z, rotate

* LICENSE
  :PROPERTIES:
  :rotate-y: 51
  :trans-x:  1000
  :trans-z:  500
  :END:

  Licensed under the GPLv3 license.
